const countries = [
    'IJsland',
    'Ierland',
    'Verenigd Koningkrijk',
    'Noorwegen',
    'Zweden',
    'Finland',
    'Denemarken',
    'Duitsland',
    'België',
    'Luxemburg',
    'Frankrijk',
    'Spanje',
    'Portugal',
    'Italië',
    'Zwitserland',
    'Oostenrijk',
    'Polen',
    'Tsjechië',
    'Slowakije',
    'Hongarije',
    'Slovenië',
    'Kroatië',
    'Bosnië en Hercegovina',
    'Servië',
    'Montenegro',
    'Kosovo',
    'Albanië',
    'Noord-Macedonië',
    'Griekenland',
    'Estland',
    'Letland',
    'Litouwen',
    'Wit Rusland',
    'Oekraïne',
    'Moldavië',
    'Roemenië',
    'Bulgarije',
    'Rusland'
];


const citys = [
    { name: 'IJsland', h: 'Reykjavik' },
    { name: 'Ierland', h: 'Dublin' },
    { name: 'Verenigd Koningkrijk', h: 'Londen' }, 
    { name: 'Noorwegen', h: 'Oslo' },
    { name: 'Zweden', h: 'Stockholm' },
    { name: 'Finland', h: 'Helsinki' },
    { name: 'Denemarken', h: 'Kopenhagen' },
    { name: 'Duitsland', h: 'Berlijn' },
    { name: 'België', h: 'Brussel' },
    { name: 'Luxemburg', h: 'Luxemburg-stad' },
    { name: 'Frankrijk', h: 'Parijs' },
    { name: 'Spanje', h: 'Madrid' },
    { name: 'Portugal', h: 'Lissabon' },
    { name: 'Italië', h: 'Rome' },
    { name: 'Zwitserland', h: 'Bern' },
    { name: 'Oostenrijk', h: 'Wenen' },
    { name: 'Polen', h: 'Warschau' },
    { name: 'Tsjechië', h: 'Praag' },
    { name: 'Slowakije', h: 'Bratislava' },
    { name: 'Hongarije', h: 'Budapest' },
    { name: 'Slovenië', h: 'Ljubljana' },
    { name: 'Kroatië', h: 'Zagreb' },
    { name: 'Bosnië en Hercegovina', h: 'Sarajevo' },
    { name: 'Servië', h: 'Belgrado' },
    { name: 'Montenegro', h: 'Podgorica' },
    { name: 'Kosovo', h: 'Pristina' },
    { name: 'Albanië', h: 'Tirana' },
    { name: 'Noord-Macedonië', h: 'Skopje' },      
    { name: 'Griekenland', h: 'Athene' },
    { name: 'Estland', h: 'Talinn' },
    { name: 'Letland', h: 'Riga' },
    { name: 'Litouwen', h: 'Vilnius' },
    { name: 'Wit Rusland', h: 'Minsk' },
    { name: 'Oekraïne', h: 'Kiev' },
    { name: 'Moldavië', h: 'Chisinau' },
    { name: 'Roemenië', h: 'Boekarest' },
    { name: 'Bulgarije', h: 'Sofia' },
    { name: 'Rusland', h: 'Moskou' }
]